manifest:
  remotes:
    - name: zmkfirmware
      url-base: url-base: https://github.com/zmkfirmware
    - name: nicole208
      url-base: https://github.com/nicole208
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: main
      remote: nicole208
      revision: main
  self:
    path: config
